services:
  localai:
    image: localai/localai:v2.25.0-cublas-cuda12-ffmpeg
    container_name: localai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:8080"
    volumes:
      - ../models-localai:/models
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
    environment:
      - MODELS_PATH=/models
      - DEBUG=true
      - NVIDIA_DISABLE_REQUIRE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LOCALAI_FORCE_META_BACKEND_CAPABILITY=nvidia
      - CUDA_VISIBLE_DEVICES=0
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu
    restart: unless-stopped